### ISSUE TITLE
Add transaction mapping to accounts

### ISSUE THREAD

**Issue by andrecronje** [andrecronje/lachesis#13]
Allow transactions to be mapped to accounts (send & receive) and stored inmem and in db

**Comment by AgustinCB** [comment]
I'll start working on this in https://github.com/AgustinCB/lachesis/tree/issue-13. Expect to complete in a couple days. Collaborations welcomed!

**Comment by andrecronje** [comment]
Will move this over to a custom EVM implementation instead of a babble implementation.
