### ISSUE TITLE
Replace all JSON with FlatBuffers (or similar)

### ISSUE THREAD

**Issue by SamuelMarks** [andrecronje/lachesis#55]
**Is your feature request related to a problem? Please describe.**
JSON is really slow. Performance analysis of the codebase, shows JSON marshalling as one of the bottlenecks:

![pprof001](https://user-images.githubusercontent.com/807580/47404999-4ad25080-d79b-11e8-9b38-a441aab325b8.png)

**Describe the solution you'd like**
One option: https://google.github.io/flatbuffers

Open to alternatives.

**Describe alternatives you've considered**
Protocol buffers, JSON, JSONB, Cap'n proto, Apache Avro, Apache Thrift.

**Additional context**
See also: https://en.wikipedia.org/wiki/Comparison_of_data_serialization_formats

We can still accept JSON, but let's force everything to convert to some faster-marshalling format.

**Comment by SamuelMarks** [comment]
Actually, since we're qRPC, let's use protocol buffers. There are a couple of Rust implementations also, for down the track.

**Comment by AgustinCB** [comment]
Picking this one to work on.

**Comment by SamuelMarks** [comment]
Looking better:
![lachesis-pprof002](https://user-images.githubusercontent.com/807580/48328765-a2c4ee80-e699-11e8-936d-fb64f7071ef7.png)
