### ISSUE TITLE
tests on ./src/net/client_websocket_test.go timeout

### ISSUE THREAD

**Issue by AgustinCB** [andrecronje/lachesis#58]
**Describe the bug**
If you type:

```bash
go test ./src/net/...
```

If you wait long enough, you get:

```
SIGQUIT: quit
PC=0x45f9f1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0xfcb980, 0x80, 0x0, 0x0, 0x0, 0x7ffe00000000, 0x0, 0x0, 0x7ffeea230f08, 0x40c472, ...)
	/opt/go/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0xfcb980, 0x7ffe00000000, 0xffffffffffffffff)
	/opt/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0xfcb980)
	/opt/go/src/runtime/lock_futex.go:151 +0xa2
runtime.stoplockedm()
	/opt/go/src/runtime/proc.go:2165 +0x8a
runtime.schedule()
	/opt/go/src/runtime/proc.go:2565 +0x2d9
runtime.park_m(0xc0001ae300)
	/opt/go/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
	/opt/go/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001b6100, 0xae2158, 0x13, 0xafe670, 0x47d816)
	/opt/go/src/testing/testing.go:879 +0x37a
testing.runTests.func1(0xc0001b6000)
	/opt/go/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0001b6000, 0xc000165e08)
	/opt/go/src/testing/testing.go:827 +0xbf
testing.runTests(0xc00018e0a0, 0xfc1280, 0xd, 0xd, 0x40d71f)
	/opt/go/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc000196180, 0x0)
	/opt/go/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:66 +0x13d

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	/opt/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/opt/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/opt/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 35 [chan receive]:
github.com/andrecronje/lachesis/src/net.TestClientWebSocket(0xc0001b6100)
	/opt/go/src/github.com/andrecronje/lachesis/src/net/client_websocket_test.go:79 +0x282
testing.tRunner(0xc0001b6100, 0xafe670)
	/opt/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/opt/go/src/testing/testing.go:878 +0x353

rax    0xca
rbx    0xfcb840
rcx    0x45f9f3
rdx    0x0
rdi    0xfcb980
rsi    0x80
rbp    0x7ffeea230ed0
rsp    0x7ffeea230e88
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc
r13    0xff
r14    0xb907b6
r15    0x0
rip    0x45f9f1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/andrecronje/lachesis/src/net	600.005s
```

**To Reproduce**

See above.

**Expected behavior**
The test should finish (hopefully in less than a second).

**Comment by rishflab** [comment]
I'll have a look into this tommorow

**Comment by s4kibs4mi** [comment]
@rishflab to test client `addr` parameter you are passing is the address of websocket server and the server must be up and running to test client. In test case 10 messages exchange happens between server and client and both go off.

**Comment by rishflab** [comment]
Hey thanks for you response.
The tests pass when i run the server test and the client tests sequentially but the processes still hang. Gracefulshutdown doesn’t seem to work on my machine, does it work on yours? (I’m running Ubuntu 18.04)
Also we are setting up CI/CD and these tests won’t work there as  must run in a specific order which cannot be guaranteed.

**Comment by s4kibs4mi** [comment]
@rishflab I have tested on my machine (macOS Mojave) and it worked. To test client its mandatory to run server first. So what we can do is running server within client test other than depending on server test, in same way in server test have to add client test stuffs.

**Comment by AgustinCB** [comment]
Uh, if the client needs the server to be or if some order is required, then this is not a unit test any more (which is what `go test` assumes).

Is there a way we can mock the server? If not, maybe we can move this test out of the unit test chain and make some kind of integration test?

**Comment by rishflab** [comment]
Yeh we should make this sort of test an integration test. 

I don't think the websocket server is currently being used anywhere in the codebase. I removed it along with many other unused transports and everything seems to be running. I don't think it should be in master unless it is being used in master. It is unneccesary cognitive overhead and maintenance burden.

If it is part of an incomplete feature it should probably sit in that feature branch until it is complete.

**Comment by s4kibs4mi** [comment]
@rishflab the purpose of test was to clarify the usage. And so far I can remember @andrecronje told me that it will be used to send events within nodes. Not sure if we are still on the track or decided something else to use.

**Comment by rishflab** [comment]
Yeh im curious myself, because i think gRPC is being used for internode communication, not 100% sure.

**Comment by quan8** [comment]
Hi, plz leave comments to help understand or resolve the issue.
@s4kibs4mi which issue does those new files belong to?
Agree with @AgustinCB. The tests need to be rewritten. In general, every test should not depend on any other tests.

**Comment by SamuelMarks** [comment]
Agreed. Unit tests should be independent, and finish rapidly.

The distinction is made clearly by Martin Fowler, between Sociable Tests and Solitary Tests.
https://martinfowler.com/bliki/UnitTest.html
(referencing Jay Fields, who originated these terms in https://leanpub.com/wewut)

**We want only Solitary Tests to run from `go test`.**

**Comment by s4kibs4mi** [comment]
I will rewrite the tests.
@quan8 @andrecronje can clarify.
