### ISSUE TITLE
Limit on grpc message size

### ISSUE THREAD

**Issue by Maxime2** [andrecronje/lachesis#62]
I have tried lachesis version after https://github.com/andrecronje/lachesis/pull/59 with CI/CD check script scripts/multi.bash and got a bunch of errors like these:

WARN[0036] recv from server err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (48900172 vs. 4194304)
WARN[0036] recv from server err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (48900172 vs. 4194304)
WARN[0036] recv from server err: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (48900172 vs. 4194304)

it looks like we are hitting here the default MaxReceiveMessageSize limitation in grpc: https://github.com/grpc/grpc-go/blob/master/clientconn.go#L96

Perhaps we need add limitation on block size in lachesis to fit inside this limit.

**Comment by devintegral** [comment]
I hope, that error will disappear after the [PR #65](https://github.com/andrecronje/lachesis/pull/65) merged.
