### ISSUE TITLE
Subscriber based block subscription

### ISSUE THREAD

**Issue by andrecronje** [andrecronje/lachesis#7]
Current proxy connection is a synchronous between two endpoints, change to a subscription based MQTT/WS model to facilitate block/transaction transfers

**Comment by rishflab** [comment]
Hi, is this issue still relevant now that GrpcAppProxy has been introduced?

`
func (p *GrpcAppProxy) send_events4clients() {
	var (
		err       error
		connected []ClientStream
		alive     []ClientStream
		stream    ClientStream
	)
	for event := range p.event4clients {

		for i := len(p.new_clients); i > 0; i-- {
			stream = <-p.new_clients
			connected = append(connected, stream)
		}

		for _, stream = range connected {
			err = stream.Send(event)
			if err == nil {
				alive = append(alive, stream)
			}
		}

		connected = alive
		alive = nil
	}
}
`
This function seems to be pushing events to registered/subscribed clients ?
